name: backdoor-crit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - statsmodels
  - scipy
  - graphviz           # ← Graphviz binaries
  - python-graphviz    # ← the Python wrapper
  - pip
  - pip:
    - networkx
