name: bayesian-regression-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10  
  - pandas
  - numpy
  - plotly
  - matplotlib
  - seaborn
  - statsmodels
  - scikit-learn
  - pymc          
  - arviz           
  - linearmodels
  - pip
  - pip:
      - causalpy
      - causaldata
