# File: environment.yml

name: causal-forest-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pip
  - pip:
    - econml
    - causalml
